# ______    _     _____ _                 
# | ___ \  | |   /  ___| |                
# | |_/ /__| |_  \ `--.| |_ ___  _ __ ___ 
# |  __/ _ \ __|  `--. \ __/ _ \| '__/ _ \
# | | |  __/ |_  /\__/ / || (_) | | |  __/
# \_|  \___|\__| \____/ \__\___/|_|  \___|
#                                         
                                       
openapi: "3.0.0"
info:
  version: 1.0.0
  title: CQRS Petstore
  description: An example project used to show a CQRS implementation that highlights the utility of using Mediatr, Autofac's IOC container, OpenAPI's scaffolding abilities, and general CQRS ideas.
  license:
    name: MIT
servers:
  - url: https://localhost:44321/API #this will change.
paths:
  /pets:
    get:
      summary: List pets
      operationId: listPets
      tags:
        - query
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
        - name: offset
          in: query
          description: Defines the "page". The size of this page is indicated by the `limit` parameter. 
          required: false
          schema:
            maximum: 100
            type: integer
            format: int32
        - name: sorts
          in: query
          description: Comma delimited `PetSortValue` enums. If no sort parameters specified, the default will be the pet name asc
          required: false
          schema:
            type: string
            pattern: '\w+(,\w+)*' #  don't allow whitespaces around the comma
        - name: namesToFilterBy
          in: query
          description: Comma delimited string of Pet Names. 
          required: false
          schema:
            type: string
            pattern: '\w+(,\w+)*' #  don't allow whitespaces around the comma
        - name: typesToFilterBy
          in: query
          description: Comma delimited `PetTypeValue` enums. If no sort parameters specified, the default will be the pet name asc
          required: false
          schema:
            type: string
            pattern: '\w+(,\w+)*' #  don't allow whitespaces around the comma
      responses:
        '200':
          description: A paged array of pets
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/PetCollection"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PetStoreError"
    post:
      summary: Create a pet
      operationId: createPet
      tags:
        - command
      requestBody:
        description: A Pet object we wish to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
      responses:
        '200':
          description: Updated pet object. The ResourceID should be updated.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PetStoreError"
  /pets/{petId}:
    get:
      summary: Info for a specific pet
      operationId: showPetById
      tags:
        - query
      parameters:
        - name: petId
          in: path
          required: true
          description: The id of the pet to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PetStoreError"
components:
  schemas:
    
    # ============
    #   ENUMS
    # ============

    PetStoreErrorValue:
      description: List of all errors you'll encounter with PetStore
      type: string
      enum:        
        - Could not create a Pet
        - Pet cannot be found
        - Pet cannot be null
        - Pet ID is not unique
        - Pet Name is required
        - Pet Resource ID must be 00000000-0000-0000-0000-000000000000 when creating a Pet
        - Pet Resource IDs do not match
        - Pet Resource ID is required
        - Pet Type has an invalid value
        - Pet Type is required
        - PetStore has the following validation errors

    PetTypeValue:
      description: Type of Pet
      type: string
      enum:        
        - Bat
        - Cat
        - Dog
        - Goat
        - Monkey
        - Rock
        - Sloth

    PetSortType:
      description: For the front end to append the correct ending for creating sort objects. _ASC = ascending, and _DESC = decending.
      type: string
      enum:
        - _ASC
        - _DESC

    PetSortValue:
      description: Fields that we can sort on for server-side sorting.
      type: string
      enum:        
        - Name_ASC # name ascending
        - Name_DESC # name descending
        - Type_ASC
        - Type_DESC
    
    # ============
    #   Objects
    # ============

    Pet:
      type: object
      description: The main Entity we are interested in.
      required:
        - resourceID
        - name
        - type
      properties:
        resourceID:
          description: Resource ID. Unique and readonly.
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
        type:
          nullable: true # pro tip: make your enums nullable so if they don't serialize correctly they won't default to the first enum incorrectly.
          default: null
          $ref: "#/components/schemas/PetTypeValue"

    PetCollection:
      type: object
      description: An aggregate object that allows us to pass back the paging information (including the total number of pets) for a potentially filtered collection of Pets
      required:
        - total
        - pets
      properties:
        offset:
          type: integer
          format: int32
          nullable: true
          description: Offset of the collection. Which is optional.
          minimum: 0
        pageSize:
          type: integer
          format: int32
          nullable: true
          description: How many are in the current selection. Which is optional.
          minimum: 0
        total:
          type: integer
          format: int32
          description: The total number of Pets in this set.
          minimum: 0
        pets:
          description: The returned Pets
          type: array
          items:
            $ref: "#/components/schemas/Pet"
    
    PetStoreError:
      description: This object is how we are communicating validation errors to the front end.  
      type: object
      properties:
        code:
          $ref: '#/components/schemas/PetStoreErrorValue'
          description: Internal error code
        message:
          type: string
        errors:             # NOTE: The following is a declaration of an IDictionary (an Associative Array). Looks like it's not, but it is.
          type: object
          description: A dictionary of error messages for specific fields. The keys will be the IDs of html elements that had errors. 
          additionalProperties:
            $ref: '#/components/schemas/PetStoreErrorValue'


# APPENDIX:
#
# ASCI Font URL: https://patorjk.com/software/taag/#p=display&f=Doom&t=Test
#