//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.13.1.0 (NJsonSchema v10.5.1.0 (Newtonsoft.Json v12.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

using System.Linq;

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"

namespace Petstore.Common.Command
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "13.13.1.0 (NJsonSchema v10.5.1.0 (Newtonsoft.Json v12.0.0.0))")]
    [Microsoft.AspNetCore.Mvc.Route("API")]
    public abstract class QueryControllerBase : Microsoft.AspNetCore.Mvc.ControllerBase
    {
        /// <summary>List pets</summary>
        /// <param name="limit">How many items to return at one time (max 100)</param>
        /// <param name="offset">Defines the "page". The size of this page is indicated by the `limit` parameter.</param>
        /// <param name="sorts">Comma delimited `PetSortValue` enums. If no sort parameters specified, the default will be the pet name asc</param>
        /// <param name="namesToFilterBy">Comma delimited string of Pet Names.</param>
        /// <param name="typesToFilterBy">Comma delimited `PetTypeValue` enums. If no sort parameters specified, the default will be the pet name asc</param>
        /// <returns>A paged array of pets</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("pets")]
        public abstract System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<PetCollection>> ListPets([Microsoft.AspNetCore.Mvc.FromQuery] int? limit, [Microsoft.AspNetCore.Mvc.FromQuery] int? offset, [Microsoft.AspNetCore.Mvc.FromQuery] string sorts, [Microsoft.AspNetCore.Mvc.FromQuery] string namesToFilterBy, [Microsoft.AspNetCore.Mvc.FromQuery] string typesToFilterBy, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
    
        /// <summary>Info for a specific pet</summary>
        /// <param name="petId">The id of the pet to retrieve</param>
        /// <returns>Expected response to a valid request</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("pets/{petId}")]
        public abstract System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<Pet>> ShowPetById([Microsoft.AspNetCore.Mvc.ModelBinding.BindRequired] string petId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NSwag", "13.13.1.0 (NJsonSchema v10.5.1.0 (Newtonsoft.Json v12.0.0.0))")]
    [Microsoft.AspNetCore.Mvc.Route("API")]
    public abstract class CommandControllerBase : Microsoft.AspNetCore.Mvc.ControllerBase
    {
        /// <summary>Create a pet</summary>
        /// <param name="body">A Pet object we wish to create</param>
        /// <returns>Updated pet object. The ResourceID should be updated.</returns>
        [Microsoft.AspNetCore.Mvc.HttpPost, Microsoft.AspNetCore.Mvc.Route("pets")]
        public abstract System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<Pet>> CreatePet([Microsoft.AspNetCore.Mvc.FromBody] [Microsoft.AspNetCore.Mvc.ModelBinding.BindRequired] Pet body, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
    
    }

    /// <summary>List of all errors you'll encounter with PetStore</summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.5.1.0 (Newtonsoft.Json v12.0.0.0)")]
    public enum PetStoreErrorValue
    {
        [System.Runtime.Serialization.EnumMember(Value = @"Could not create a Pet")]
        Could_not_create_a_Pet = 0,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Pet cannot be found")]
        Pet_cannot_be_found = 1,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Pet cannot be null")]
        Pet_cannot_be_null = 2,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Pet ID is not unique")]
        Pet_ID_is_not_unique = 3,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Pet Name is required")]
        Pet_Name_is_required = 4,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Pet Resource ID must be 00000000-0000-0000-0000-000000000000 when creating a Pet")]
        Pet_Resource_ID_must_be_00000000000000000000000000000000_when_creating_a_Pet = 5,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Pet Resource IDs do not match")]
        Pet_Resource_IDs_do_not_match = 6,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Pet Resource ID is required")]
        Pet_Resource_ID_is_required = 7,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Pet Type has an invalid value")]
        Pet_Type_has_an_invalid_value = 8,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Pet Type is required")]
        Pet_Type_is_required = 9,
    
        [System.Runtime.Serialization.EnumMember(Value = @"PetStore has the following validation errors")]
        PetStore_has_the_following_validation_errors = 10,
    
    }
    
    /// <summary>Type of Pet</summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.5.1.0 (Newtonsoft.Json v12.0.0.0)")]
    public enum PetTypeValue
    {
        [System.Runtime.Serialization.EnumMember(Value = @"Bat")]
        Bat = 0,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Cat")]
        Cat = 1,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Dog")]
        Dog = 2,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Goat")]
        Goat = 3,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Monkey")]
        Monkey = 4,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Rock")]
        Rock = 5,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Sloth")]
        Sloth = 6,
    
    }
    
    /// <summary>For the front end to append the correct ending for creating sort objects. _ASC = ascending, and _DESC = decending.</summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.5.1.0 (Newtonsoft.Json v12.0.0.0)")]
    public enum PetSortType
    {
        [System.Runtime.Serialization.EnumMember(Value = @"_ASC")]
        _ASC = 0,
    
        [System.Runtime.Serialization.EnumMember(Value = @"_DESC")]
        _DESC = 1,
    
    }
    
    /// <summary>Fields that we can sort on for server-side sorting.</summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.5.1.0 (Newtonsoft.Json v12.0.0.0)")]
    public enum PetSortValue
    {
        [System.Runtime.Serialization.EnumMember(Value = @"Name_ASC")]
        Name_ASC = 0,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Name_DESC")]
        Name_DESC = 1,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Type_ASC")]
        Type_ASC = 2,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Type_DESC")]
        Type_DESC = 3,
    
    }
    
    /// <summary>The main Entity we are interested in.</summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.5.1.0 (Newtonsoft.Json v12.0.0.0)")]
    public partial class Pet 
    {
        /// <summary>Resource ID. Unique and readonly.</summary>
        [Newtonsoft.Json.JsonProperty("resourceID", Required = Newtonsoft.Json.Required.Always)]
        public System.Guid ResourceID { get; set; }
    
        [Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.Always)]
        public string Name { get; set; }
    
        [Newtonsoft.Json.JsonProperty("type", Required = Newtonsoft.Json.Required.AllowNull)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public PetTypeValue? Type { get; set; }
    
        private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();
    
        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties; }
            set { _additionalProperties = value; }
        }
    
        public string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, new Newtonsoft.Json.JsonSerializerSettings());
        }
    
        public static Pet FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<Pet>(data, new Newtonsoft.Json.JsonSerializerSettings());
        }
    
    }
    
    /// <summary>An aggregate object that allows us to pass back the paging information (including the total number of pets) for a potentially filtered collection of Pets</summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.5.1.0 (Newtonsoft.Json v12.0.0.0)")]
    public partial class PetCollection 
    {
        /// <summary>Offset of the collection. Which is optional.</summary>
        [Newtonsoft.Json.JsonProperty("offset", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int? Offset { get; set; }
    
        /// <summary>How many are in the current selection. Which is optional.</summary>
        [Newtonsoft.Json.JsonProperty("pageSize", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int? PageSize { get; set; }
    
        /// <summary>The total number of Pets in this set.</summary>
        [Newtonsoft.Json.JsonProperty("total", Required = Newtonsoft.Json.Required.Always)]
        public int Total { get; set; }
    
        /// <summary>The returned Pets</summary>
        [Newtonsoft.Json.JsonProperty("pets", Required = Newtonsoft.Json.Required.Always)]
        public System.Collections.Generic.List<Pet> Pets { get; set; } = new System.Collections.Generic.List<Pet>();
    
        private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();
    
        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties; }
            set { _additionalProperties = value; }
        }
    
        public string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, new Newtonsoft.Json.JsonSerializerSettings());
        }
    
        public static PetCollection FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<PetCollection>(data, new Newtonsoft.Json.JsonSerializerSettings());
        }
    
    }
    
    /// <summary>This object is how we are communicating validation errors to the front end.</summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.5.1.0 (Newtonsoft.Json v12.0.0.0)")]
    public partial class PetStoreError 
    {
        /// <summary>Internal error code</summary>
        [Newtonsoft.Json.JsonProperty("code", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public PetStoreErrorValue Code { get; set; }
    
        [Newtonsoft.Json.JsonProperty("message", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Message { get; set; }
    
        /// <summary>A dictionary of error messages for specific fields. The keys will be the IDs of html elements that had errors.</summary>
        [Newtonsoft.Json.JsonProperty("errors", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.IDictionary<string, PetStoreErrorValue> Errors { get; set; }
    
        private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();
    
        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties; }
            set { _additionalProperties = value; }
        }
    
        public string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, new Newtonsoft.Json.JsonSerializerSettings());
        }
    
        public static PetStoreError FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<PetStoreError>(data, new Newtonsoft.Json.JsonSerializerSettings());
        }
    
    }

}

#pragma warning restore 1591
#pragma warning restore 1573
#pragma warning restore  472
#pragma warning restore  114
#pragma warning restore  108
#pragma warning restore 3016